project:
  type: website
  output-dir: docs

website:
  title: "BitsToBytesBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
fontsize: 1.1em
fontcolor: "#FFFFFF"  # Dark white text color
linkcolor: "#007bff"  # Blue hyperlink color
backgroundcolor: "#113f4d"  # Light teal-blue background
mainfont: "Roboto, Lato"  # Retro font

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

